with team_stats as (
    select *,
    from {{ ref("stg-team-stats") }}
),
teams as (
    select *,
    from {{ ref("teams") }}
)
select 
    team_stats.team_id,
    team_stats.stats__goal,
    team_stats.stats__total_shot,
    team_stats.stats__shot_on_target,
    team_stats.stats__shot_off_target,
    team_stats.stats__shot_blocked,
    team_stats.stats__shot_in_pa,
    team_stats.stats__shot_outside_of_pa,
    team_stats.stats__free_kick,
    team_stats.stats__corner_kick,
    team_stats.stats__throw_in,
    team_stats.stats__penalty_kick,
    team_stats.stats__pass,
    team_stats.stats__pass_succeeded,
    team_stats.stats__pass_failed,
    team_stats.stats__assist,
    team_stats.stats__key_pass,
    team_stats.stats__control_under_pressure,
    team_stats.stats__cross,
    team_stats.stats__cross_succeeded,
    team_stats.stats__final_third_area_pass,
    team_stats.stats__final_third_area_pass_succeeded,
    team_stats.stats__middle_area_pass,
    team_stats.stats__middle_area_pass_succeeded,
    team_stats.stats__defensive_area_pass,
    team_stats.stats__defensive_area_pass_succeeded,
    team_stats.stats__short_pass,
    team_stats.stats__short_pass_succeeded,
    team_stats.stats__medium_range_pass,
    team_stats.stats__medium_range_pass_succeeded,
    team_stats.stats__long_pass,
    team_stats.stats__long_pass_succeeded,
    team_stats.stats__forward_pass,
    team_stats.stats__forward_pass_succeeded,
    team_stats.stats__backward_pass,
    team_stats.stats__backward_pass_succeeded,
    team_stats.stats__sideways_pass,
    team_stats.stats__sideways_pass_succeeded,
    team_stats.stats__tackle,
    team_stats.stats__tackle_succeeded,
    team_stats.stats__aerial_duel,
    team_stats.stats__aerial_duel_succeeded,
    team_stats.stats__aerial_duel_failed,
    team_stats.stats__ground_duel,
    team_stats.stats__ground_duel_succeeded,
    team_stats.stats__ground_duel_failed,
    team_stats.stats__loose_ball_duel,
    team_stats.stats__loose_ball_duel_succeeded,
    team_stats.stats__loose_ball_duel_failed,
    team_stats.stats__intercept,
    team_stats.stats__clearance,
    team_stats.stats__recovery,
    team_stats.stats__intervention,
    team_stats.stats__take_on,
    team_stats.stats__take_on_succeeded,
    team_stats.stats__mistake,
    team_stats.stats__block,
    team_stats.stats__foul,
    team_stats.stats__foul_won,
    team_stats.stats__offside,
    team_stats.stats__yellow_card,
    team_stats.stats__red_card,
    team_stats.stats__own_goal,
    team_stats.stats__goal_conceded,
    team_stats.stats__goal_kick,
    team_stats.stats__goal_kick_succeeded,
    team_stats.stats__aerial_clearance,
    team_stats.stats__aerial_clearance_succeeded,
    team_stats.stats__aerial_clearance_failed,
    team_stats.stats__defensive_line_support,
    team_stats.stats__defensive_line_support_succeeded,
    team_stats.stats__defensive_line_support_failed,
    team_stats.stats__save_by_catching,
    team_stats.stats__possession,
    team_stats.match_id,
    team_stats._dlt_id,
    teams.team_name
from team_stats
inner join teams
on team_stats.team_id = teams.team_id
